### ISSUE TITLE
Commenti a Utils.py

### ISSUE THREAD

**Issue by iannellog** [lucabracaglia/TOMBOLA#1]
Aggiungete dei valori di default per gli argomenti sulla linea di comando altrimenti il programma va in errore se uno lo lancia senza opzioni. 

In alternativa il programma potrebbe riconoscere che le variabili corrispondenti ai parametri hanno il valore None e stampare un avviso che suggerisce all utente di usare l'opzione -h per sapere come usare correttamente il programma.

**Comment by iannellog** [comment]
Il problema non è completamente risolto. Per evitare che il programma vada in errore, dopo aver stampato il messaggio:

> Digita -h per vedere gli argomenti da inserire sulla linea di comando

dovreste far terminare il programma (mi pare che si può usare 'exit' o qualcosa di simile, cercate su google).

**Comment by lucabracaglia** [comment]
buongiorno professore,
abbiamo provveduto a modificare quanto da lei sottolineato. Abbiamo inserito anche dei casi di test per rendere più comprensibile i vari casi inerenti all'inserimento degli argomenti sulla linea di comando
